# theme: jekyll-theme-cayman
theme: jekyll-theme-minimal
title: Requirement and Model-Driven Engineering (RAMDE) -- under development
description: CISTER-ISEP MScCCSE 2021/2022
show_downloads: false
logo: http://cister-labs.pt/mscccse/logo.png